// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Number.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(global, r)
{
    var require = typeof(r) === "function" ? r : function(){};
    require("Ice/Object");
    require("Ice/ObjectPrx");
    require("Ice/Operation");
    require("Ice/Long");
    require("Ice/HashMap");
    require("Ice/HashUtil");
    require("Ice/ArrayUtil");
    require("Ice/StreamHelpers");
    
    var Ice = global.Ice || {};
    var Demo = global.Demo ||  {};

    Demo.Number = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 0,
        [
            "::Demo::Number",
            "::Ice::Object"
        ],
        -1, undefined, undefined, false);

    Demo.NumberPrx = Slice.defineProxy(Ice.ObjectPrx, Demo.Number.ice_staticId, undefined);

    Slice.defineOperations(Demo.Number, Demo.NumberPrx,
    {
        "getNumber": [, 2, 2, , , [3], , , , , ]
    });
    global.Demo = Demo;
}
(typeof (global) === "undefined" ? window : global, typeof (require) === "undefined" ? undefined : require));
